apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-plus-ingress-rc
  labels:
    app: nginx-plus-ingress
spec:
  replicas: 1
  selector:
    app: nginx-plus-ingress
  template:
    metadata:
      labels:
        app: nginx-plus-ingress
    spec:
      containers:
      - image: gcr.io/nginx-dev-ingress/nginx-plus-ingress:0.2
        imagePullPolicy: Always
        name: nginx-plus-ingress
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        - containerPort: 8080
          hostPort: 8080
        # turns on extensive logging including printing out generated NGINX conf files
        # args:
        #  - -v=3
